version: '3.1'

services:

  grafana:
    image: grafana/grafana:9.3.8
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_DEFAULT_APP_MODE: "development"
      GF_DATAPROXY_LOGGING: "true"
      GF_LOG_LEVEL: "debug"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./:/var/lib/grafana/plugins/globocom-youbora-datasource

  js-builder:
    build:
      context: .
      dockerfile: Dockerfile.node
    restart: always
    volumes:
      - ./dist/:/tmp/grafana/dist/
    entrypoint: /bin/sh -c
    command: yarn build

  go-builder:
    build:
      context: .
      dockerfile: Dockerfile.golang
    restart: always
    volumes:
      - ./dist/:/tmp/grafana/dist/
    entrypoint: /bin/sh -c
    command: mage build:linux

  console:
    image: grafana/grafana:9.3.8
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/var/lib/grafana/plugins/youbora-datasource
    environment:
      GF_DEFAULT_APP_MODE: "development"
    entrypoint: /bin/sh -c
    command: /bin/bash

volumes:
  grafana-data: